/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HR_UI;

import HRModel.EmpProfileHistory;
import HRModel.EmployeeProfile;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author adity
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
         EmpProfileHistory emphistory;

    public CreateJPanel(EmpProfileHistory emphistory) {
        initComponents();
        this.emphistory=emphistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblSDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        lblTeamInfo = new javax.swing.JLabel();
        txtTeamInfo = new javax.swing.JTextField();
        lblPosTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        lblPhNo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblEmpID = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtPhNo = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        datechooser = new com.toedter.calendar.JDateChooser();

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add the New Employee....");

        lblSDate.setText("Start Date");

        lblLevel.setText("Level Number");

        lblTeamInfo.setText("Team Info");

        lblPosTitle.setText("Title *");

        lblPhNo.setText("Phone Number");

        lblName.setText("Name *");

        btnSubmit.setText("Create");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblEmpID.setText("Employee ID *");

        lblAge.setText("Age in Digits");

        txtAge.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAge.setName(""); // NOI18N

        lblGender.setText("Gender");

        lblEmail.setText("Email Address *");

        btnBrowse.setText("Browse Photo");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpID)
                            .addComponent(lblName)
                            .addComponent(lblAge)
                            .addComponent(lblGender)
                            .addComponent(lblSDate))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmpID)
                            .addComponent(txtName)
                            .addComponent(txtAge)
                            .addComponent(txtGender)
                            .addComponent(datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)))
                    .addComponent(lblPhNo)
                    .addComponent(lblEmail)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBrowse)
                        .addGap(52, 52, 52)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSubmit))
                    .addComponent(lblPosTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTeamInfo)
                            .addComponent(lblLevel))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                            .addComponent(txtTeamInfo)
                            .addComponent(txtTitle)
                            .addComponent(txtPhNo)
                            .addComponent(txtEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpID)
                    .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSDate)
                    .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLevel)
                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeamInfo)
                    .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhNo)
                    .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 35, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnBrowse)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents
String name;
String empID;
int age;
int level;
String team_Info;
String title;
long phNo;
String email;
String gender;
String photo;
String selectedImagePath;
Date date;
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try{
        name= txtName.getText();
        empID = txtEmpID.getText();
        age = Integer.parseInt(txtAge.getText());
        gender = txtGender.getText();
        date = datechooser.getDate();
        level = Integer.parseInt(txtLevel.getText());
        team_Info = txtTeamInfo.getText();
        title = txtTitle.getText();
        phNo = Long.parseLong(txtPhNo.getText());
        email = txtEmail.getText();
        /*String photo = txtPhoto.getText();*/
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(this, "Please enter correct values..!!");
            }
     
        /*if(!(email.contains("@"))||email.isBlank()|| empID.isBlank()||!(email.endsWith(".com"))||title.isBlank()|| name.isBlank()){
            JOptionPane.showMessageDialog(this, "Enter the required details");
        }*/
        
        if(checkfield())
        {
            
            EmployeeProfile ep= emphistory.addEmployee();
            ep.setAge(age);
            ep.setDate(date);
            ep.setEmail(email);
            ep.setEmpID(empID);
            ep.setGender(gender);
            ep.setLevel(level);
            ep.setName(name);
            ep.setPhNo(phNo);
            ep.setPhoto(selectedImagePath);
            ep.setTeam_Info(team_Info);
            ep.setTitle(title);

            JOptionPane.showMessageDialog(this, "New Employee Added..!!");
       
        
            
            txtName.setText("");
            txtEmpID.setText("");
            txtAge.setText("");
            txtGender.setText("");
            datechooser.setDate(null);
            txtLevel.setText("");
            txtTeamInfo.setText("");
            txtTitle.setText("");
            txtPhNo.setText("");
            txtEmail.setText("");
            //txtPhoto.setText("");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile=new JFileChooser(); 
        //Filter Image extension
        FileNameExtensionFilter fnef= new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialog = browseImageFile.showOpenDialog(null);
        if(showOpenDialog == JFileChooser.APPROVE_OPTION){
            File selectedImageFile = browseImageFile.getSelectedFile();
            selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            
            //String uploadedPhoto = selectedImagePath;
            
            //Display Image
            ImageIcon ii= new ImageIcon(selectedImagePath);
            //Resize
            Image image=ii.getImage().getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH);
            lblPhoto.setIcon(new ImageIcon(image));
        }
        
    }//GEN-LAST:event_btnBrowseActionPerformed
    private boolean checkfield(){
        ArrayList msg = null;
        //try{
        msg= new ArrayList(0);
        if(name.isBlank()|| !(name.matches("^[a-zA-Z ]*$")))
        {
            msg.add("Please enter the name without digits or special characters but do not leave it blank");}
        if(empID.isBlank()||!(empID.matches("^[ a-zA-Z1-9_-]*$")))
         {msg.add("Please enter the ID using alphanumerics(characters like_,- are allowed)");}
        if(age<17||age>=100)
        {msg.add("Please enter the correct age between 17 and 100");}
        if(level<1||level>10)
        {msg.add("Please enter the correct level(less than 10) in digits");}
       if(!(String.valueOf(phNo).matches("^[0-9]{10}$")))
       {msg.add("Please enter the 10 digit mobile number");}
        if(team_Info!=null && (team_Info.isBlank()||!(team_Info.matches("^[ a-zA-Z1-9_-]*$"))))
         { 
             msg.add("Please enter the team Info using alphanumerics(characters like_,- are allowed)");}
        if(title!=null && (title.isBlank()|| !(title.matches("^[a-zA-Z ]*$"))))
        {msg.add("Please enter the title without digits or special characters but do not leave it blank");}
        if(email!=null && (email.isBlank()||!(email.matches("^[A-Za-z0-9+_.-]+@(.+)$"))))
        {msg.add("Please enter the correct email (xxx@xx.com)");}
        if(gender!= null && (!(gender.equalsIgnoreCase("Male")|| gender.equalsIgnoreCase("Female")|| gender.equalsIgnoreCase("Transgender")||gender.equalsIgnoreCase("M")||gender.equalsIgnoreCase("F")|| gender.equalsIgnoreCase("Others"))))
        {msg.add("Please enter either Male or Female");}
        
       //}
        /*catch(Exception e){
                System.out.println("Exception Errors Displayed in Console");
          }*/
        
        if(!(msg.isEmpty()))
        {JOptionPane.showMessageDialog(this, msg.toArray());
        msg.clear();
        return false;}
        else 
        return true;
    }
    

     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSubmit;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhNo;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPosTitle;
    private javax.swing.JLabel lblSDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhNo;
    private javax.swing.JTextField txtTeamInfo;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
